### PR TITLE
Add symmetry checking

### PR DESCRIPTION
**Pull request by Cjen1**
This PR adds permutation based symmetry checking.

It currently works by checking whether there are any permutations of the current state, who's fingerprint is within generated and in that case not persuing that state further.

This is not an efficient approach for doing symmetry checking, but for low numbers of symmetric elements, this can improve the model checking time. For an example of this test the `increment_lock.rs` example (which models multiple threads trying to increment a variable), goes from 38169180 states to 41 states. Unfortunately this takes longer to check since it fingerprints `10!` states per actual state. 

Additionally the actual interface for this feature is not very user friendly, requiring the user to manually implement a permutation function.
This may be possible to fix using hash maps.

A more efficient approach would be to canonicalise each state before fingerprinting (sort hashmaps etc by non-symmetric elements) such that two symmetric states should end up having the same hash in most cases.

TODO
- [ ] add tests
- [ ] optimise

### CODE REVIEW

**Comment by Cjen1** [comment]
This also adds nix support for reproducible build environments. (this can be stripped out though :) )

**Comment by jonnadal** [comment]
Thank you @Cjen1! This is off to a great start! I sent you a PR for some changes of my own in case you're interested: https://github.com/Cjen1/stateright/pull/1

**Comment by Cjen1** [comment]
Currently implementing both sorted and segmented approaches described here: https://link.springer.com/chapter/10.1007/10722468_1

**Comment by Cjen1** [comment]
With the sorted strategy, it makes it possible to test the increment example with 1000 threads in less than 10s on my laptop.

The idea is that you use the state of each process (which doesn't contain other process ids) to sort the array of processes.
This results in some permutation on process ids which can then be applied to the remainder of the state.

(if the state does include the other process ids then the user must ensure that they do not impact the sort. ie all process ids are equal)

Two symmetric states are likely (but not certain) to produce the same sorted main array. This is very efficient to calculate, however the initial sorting of the array may result in non-unique canonicalised states.
For example with Paxos since this approach does not take into account the sent messages, two symmetrically equivalent states may result in different canonicalised states based on the initial sorting of the array.

That being said for most scenarios this is likely to greatly reduce the state space while being very fast to calculate.

The segmented strategy may result in a better reduction, but in the worst case it results in the same performance as the Full strategy initially presented.

**Comment by jonnadal** [comment]
This is great! Thank you once again @Cjen1! Here are some follow-up commits:

1. 3f82dd7
2. 522f74e
3. db39d12
4. 8c16713
5. 420160b

**Pull request merged**
